# Generated by Django 5.2 on 2025-04-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_car_pricecar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePhone', models.CharField(max_length=30)),
                ('pricePhone', models.FloatField(blank=True, default=0)),
                ('seria', models.CharField(max_length=30)),
            ],
        ),
    ]
